
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[361] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  103,  101,
      100,  100,  100,   76,  101,   98,   67,   73,  101,   48,
       49,   66,   64,   55,   65,   52,   96,    6,    6,   81,
       54,   56,   82,   57,   80,   50,   51,   75,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   46,   74,   47,   77,  102,   99,   61,
        0,    4,    0,   98,   98,   86,   78,   90,    0,    5,
        0,   94,   85,   68,   83,   69,   84,    0,    6,    0,
        0,    1,   97,    0,    6,    0,    0,    0,    0,    6,
       70,   58,   60,   93,   59,   71,   92,   98,   98,   98,

       98,   98,   98,   12,   98,   98,   98,   98,   98,   98,
       98,   39,   98,   13,   98,   98,   98,   98,   98,   98,
       98,   98,   98,    0,   98,   98,   98,   98,   98,   91,
       79,   63,    0,    0,    0,    0,    0,    0,   98,    0,
        0,    0,    0,    0,    0,    0,   95,   53,    0,    2,
        0,    0,    2,    0,    1,    2,    6,    0,    7,    0,
        0,    6,    8,    9,   87,   62,   88,   72,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   32,   98,   98,   98,   21,   98,   98,
       98,   98,   98,   98,   98,   43,   98,   98,    0,   18,

       98,   98,   98,   98,    0,    0,    4,    0,    4,    0,
        0,    0,    0,   98,    0,    0,    0,    5,    0,    5,
        0,    0,    0,    0,    0,    0,    6,    2,    0,    1,
        0,    0,    0,    2,    2,    2,    0,    0,    6,    6,
        6,   89,   98,   98,   15,   98,   98,   98,   98,   98,
       98,   98,   16,   45,   98,   98,   98,   98,   98,   98,
       98,    3,   98,   98,   98,   37,   98,   10,   98,   98,
        0,   22,   98,   30,   98,    0,    0,    0,    0,    0,
        0,   98,    0,    0,    0,    0,    0,    0,    0,    6,
        6,    0,    1,    2,    6,    6,   44,   11,   19,   23,

       27,   98,   98,   98,   98,   98,   98,   10,   98,   98,
       98,   98,   98,   29,   98,   40,   98,   98,    0,   26,
       34,    0,    0,    0,   98,    0,    0,    0,    0,   98,
       98,   98,   41,   20,   98,   98,   98,   42,   98,   25,
       33,   14,   98,   98,   98,   98,   98,   98,   38,   24,
       28,   98,   98,   31,   35,   36,   98,   98,   17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   32,
       34,   34,   34,   34,   34,   35,   34,   34,   36,   34,
       34,   34,   37,   35,   34,   34,   34,   38,   34,   34,
       39,   40,   41,   42,    7,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   34,   52,   53,   54,   55,
       56,   57,   34,   58,   59,   60,   61,   62,   63,   64,
       65,   34,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    3,    1,    4,    5,    1,    1,    1,
        1,    1,    6,    1,    1,    1,    1,    1,    7,    8,
        8,    7,    1,    1,    1,    1,    1,    1,    7,    8,
        7,    8,    8,    5,    5,    5,    5,    5,    1,    1,
        1,    9,    8,    8,    8,    8,    8,    8,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1,   10
    } ;

static const flex_int16_t yy_base[384] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  973, 1585,
     1585, 1585,  959,  935,   65,  899,  933,   63,   63, 1585,
     1585,   61,   62, 1585,   59,   60,   73,   76,   75, 1585,
     1585,   58,   74,   84, 1585, 1585, 1585,  932,   41,   57,
       73,   72,   82,   88,   93,   60,   77,   64,   92,  139,
      119,  105,  112, 1585,  110, 1585, 1585, 1585, 1585,  931,
      111, 1585,  203,  895,  249, 1585, 1585, 1585,  154, 1585,
      313,  929, 1585, 1585, 1585, 1585, 1585,  937,  169,  112,
      161,    0,  158,  163,  190,  173,  199,  176,    0,  208,
      922, 1585,  921, 1585, 1585,  205, 1585,  156,  186,  175,

      165,  184,  200,  885,  190,  884,  205,   37,  199,  185,
      889,  882,  215,  214,  222,  884,  226,  879,  153,  240,
      223,  242,  359,    0,  216,  239,  251,  244,  259, 1585,
     1585, 1585,  303,  304,  315,  218,  415,  463,  511,    0,
      318,  319,  390,  301,  550,  598, 1585, 1585,  403,  291,
      320,  357,  300,  358,    0,  378,  431,  451,  305,  363,
      394,  455,  421,    0, 1585, 1585, 1585,  907,  296,  325,
      292,  269,  367,  427,  871,  388,  340,  407,  877,  377,
      419,  430,  436,  868,  453,  443,  396,  865,  189,  864,
      454,  442,  457,  444,  877,  861,  465,  646,    0,  860,

      285,  460,  467,  466,  484,  528,  533,  692,  544,    0,
      738,  768,  798,  828,    0,  512,  513,  525,  874,  526,
        0,  920,  950,  980,  526,  542,  555,  538,  594,  560,
      595,  907,  901,  609,  700,  608,  617,  630,  634,  661,
      665, 1585,  477,  554,  857,  517,  490,  525,  572,  868,
      854,  544,  852,  851,  530,  642,  563,  579,  611,  641,
      658,  849,  850,  646,  655,  846,  647, 1010,  464, 1040,
        0,  845,  600,  844,  659,  848,  682, 1070,    0, 1118,
     1148, 1198,    0,  876,  699, 1228,    0, 1276, 1306,  704,
      714,  891, 1585, 1092,  753,  757,  842,  841,  840,  839,

      838,  660,  681,  841,  667,  677,  701,  831,  702,  741,
      683,  748,  749,  830,  730,  828,  117,  764,    0,  822,
      821, 1356,    0,  799,  765,    0, 1386,    0,  754,  805,
      670,  735,  804,  803,  747,  773,  779,  792,  705,  776,
      775,  762,  761,  794,  651,  795,  555,  763,  408,  311,
      266,  826,  746,    0,  228,   84,  829,  347,   17, 1585,
     1434, 1444, 1450, 1458, 1468, 1478, 1488, 1490, 1492, 1500,
     1510, 1514, 1522, 1532, 1542, 1552, 1556, 1558, 1566, 1570,
     1572, 1574, 1576
    } ;

static const flex_int16_t yy_def[384] =
    {   0,
      360,    1,  361,  361,  361,  361,  361,  361,  360,  360,
      360,  360,  360,  360,  362,  363,  360,  360,  364,  360,
      360,  360,  360,  360,  360,  360,  365,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  360,  360,  360,  360,  360,  360,  360,
      362,  360,  362,  363,   50,  360,  360,  360,  364,  360,
      364,  360,  360,  360,  360,  360,  360,  360,  360,  365,
      366,  367,  365,  365,  360,  360,  360,  360,  368,  360,
      360,  360,  360,  360,  360,  360,  360,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
       65,  363,  363,  363,  363,   65,  363,   65,  363,  363,
      363,  363,  363,  369,  363,  363,  363,  363,  363,  360,
      360,  360,  362,  370,  371,  362,  362,  137,  123,  372,
      364,  373,  374,  364,  364,  145,  360,  360,  360,  360,
      366,  375,  376,  366,  367,  365,  360,  360,  360,  360,
      360,  360,  360,  368,  360,  360,  360,  360,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,   65,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,   65,  363,  363,  123,  377,  363,

      363,  363,  363,  363,  362,  362,  362,  371,  362,  208,
      138,  138,  138,  123,  378,  364,  364,  364,  374,  364,
      219,  146,  146,  146,  360,  360,  360,  360,  366,  360,
      366,  376,  379,  376,  366,  365,  360,  360,  360,  360,
      360,  360,  363,  363,  363,  363,  363,  363,  363,   65,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,   65,  363,  363,  363,  363,  123,  363,  123,
      380,  363,  363,  363,  363,  371,  362,  138,  138,  138,
      138,  123,  381,  374,  364,  146,  146,  146,  146,  360,
      360,  376,  360,  366,  360,  360,  363,  363,  363,  363,

      363,  363,  363,   65,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  382,  363,
      363,  138,  281,  362,  363,  383,  146,  289,  364,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,   65,  363,  363,  363,
      363,  363,  363,  268,  363,  363,  363,  363,  363,    0,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360
    } ;

static const flex_int16_t yy_nxt[1656] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       29,   29,   30,   31,   32,   33,   34,   35,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   36,   10,
       37,   38,   39,   40,   41,   42,   43,   44,   16,   16,
       45,   16,   16,   16,   46,   16,   16,   47,   48,   49,
       50,   51,   52,   16,   53,   54,   55,   56,   57,   10,
       62,   67,   70,   72,   76,   74,   78,   65,   79,   79,
       79,   79,   91,   92,   77,   81,   73,   75,   68,  182,
       82,   85,   85,   90,   90,   90,   90,   65,   83,   93,

       94,   65,   71,   98,   63,   86,  115,   87,   87,   95,
       96,   88,   84,   89,   99,  100,   62,   65,  103,   86,
      116,   87,   87,  117,  118,  101,  119,  104,  102,  150,
      108,   88,   65,   65,  105,  130,  106,   65,  109,   89,
      112,  120,   65,  110,   65,  107,  113,  114,  111,  121,
       63,   84,   65,   65,  127,  128,  122,  123,  123,  123,
      123,  125,  129,   70,  342,   65,   80,  123,  123,  123,
      123,  123,   65,  152,  126,  150,  131,   65,  153,   65,
      156,  123,  123,  123,  123,  123,  123,   79,   79,   79,
       79,  159,  159,   71,  163,  163,  163,   84,  169,   65,

      154,  149,   84,  192,  124,  133,  134,  173,  157,  157,
      157,  157,  160,   65,  161,  149,   65,  162,  162,  162,
      162,  135,  158,   62,   85,   65,   90,   90,   90,   90,
      167,  168,  170,  171,  172,   65,  158,  360,  174,  136,
       87,  262,  184,  175,   65,   65,   65,  176,  178,   65,
       65,  136,  177,  183,   87,  136,  360,   63,  360,   65,
       65,  180,  360,  137,  181,   65,  138,  139,  139,  139,
      139,  186,  187,  200,   65,   65,   65,  139,  139,  139,
      139,  139,   65,  195,  188,  190,   65,  196,   65,  201,
      193,  139,  139,  139,  139,  139,  139,  194,  197,   65,

       65,  202,   65,  203,   65,  204,  205,  205,   62,  207,
       70,   65,  233,  246,  140,  141,  142,   61,   61,   65,
      209,  216,  216,  159,  159,   80,   65,   70,  218,   65,
      272,  143,  152,   61,   61,   61,   61,  153,  245,  228,
       71,  228,   63,  208,  228,   65,  243,  360,  234,  144,
      234,  228,   65,  234,  210,  228,   65,   71,  219,  154,
      234,  144,   80,   80,  234,  144,  360,  244,  360,   80,
      152,   65,  360,  145,  230,  235,  146,  198,  198,  198,
      198,  240,  240,  240,  240,   65,  252,  198,  198,  198,
      198,  198,   69,   69,  359,  150,  231,  154,   80,  220,

       65,  198,  198,  198,  198,  198,  198,   65,   69,   69,
       69,   69,  241,  241,  241,  241,  225,   84,  226,   65,
       62,  227,  227,  227,  227,  247,  236,   65,  236,  221,
      251,  236,  255,  211,  211,  211,  211,   65,  236,  163,
      163,  163,  236,  211,  211,  211,  211,  211,   65,  157,
      157,  157,  157,  253,   63,  261,   65,  211,  211,  211,
      211,  211,  211,  158,  237,  256,  238,   65,   65,  239,
      239,  239,  239,  162,  162,  162,  162,  158,  258,   65,
      212,  213,  213,  213,  213,  248,  249,   65,  257,   62,
       65,  213,  213,  213,  213,  213,   65,  259,  260,  267,

      264,  265,   65,   65,   65,  213,  213,  213,  213,  213,
      213,  269,  273,   65,   65,  266,  274,   65,  275,  317,
       65,   70,   70,   63,   65,   65,   65,   65,   61,  214,
      214,  214,  214,   62,   70,   70,  297,   65,   62,  214,
      214,  214,  214,  214,  290,  290,  290,  290,  300,   62,
       65,   71,   71,  214,  214,  214,  214,  214,  214,   70,
      291,  291,  291,  291,   71,   71,  299,   63,  222,  222,
      222,  222,   63,  227,  227,  227,  227,   65,  222,  222,
      222,  222,  222,   63,  301,   65,  228,  306,  228,   71,
       65,  228,  222,  222,  222,  222,  222,  222,  228,   80,

       80,  354,  228,  305,   65,  298,  152,  152,  228,  308,
      228,  153,  235,  228,   65,  223,  224,  224,  224,  224,
      228,  233,  302,   65,  228,  150,  224,  224,  224,  224,
      224,  309,   65,  154,  154,  295,  295,  295,  295,   65,
      224,  224,  224,  224,  224,  224,  320,   84,  296,  296,
      296,  296,  239,  239,  239,  239,  236,  234,  236,  234,
       65,  236,  234,   69,  270,  270,  270,  270,  236,  234,
      310,   65,  236,  234,  270,  270,  270,  270,  270,  240,
      240,  240,  240,  241,  241,  241,  241,   62,  270,  270,
      270,  270,  270,  270,  133,  134,  307,  209,  311,  315,

      312,   65,   65,  314,  321,   80,   65,   65,   70,  316,
      276,   65,  152,  333,  330,   65,  348,  153,   65,   65,
       65,   63,  290,  290,  290,  290,   61,   65,  277,  331,
       65,  210,  291,  291,  291,  291,  334,   65,   71,  154,
      277,   65,  338,   65,  277,   61,  335,   61,  294,  353,
      294,   61,  278,  294,  336,  279,  280,  280,  280,  280,
      294,   65,   65,   70,  294,   65,  280,  280,  280,  280,
      280,  295,  295,  295,  295,  296,  296,  296,  296,  341,
      280,  280,  280,  280,  280,  280,  281,  281,  281,  281,
       65,  337,  357,   71,  349,   65,  281,  281,  281,  281,

      281,   65,  339,  340,   62,  350,   65,   65,   65,   65,
      281,  281,  281,  281,  281,  281,  136,  136,  136,  136,
      355,   65,   65,   65,   65,   65,  136,  136,  136,  136,
      136,  343,  345,   65,  352,   65,   65,  351,   63,   65,
      136,  136,  136,  136,  136,  136,  282,  282,  282,  282,
       61,   61,   65,  209,   65,   65,  282,  282,  282,  282,
      282,  343,  345,   65,   65,  347,   61,   61,   61,   61,
      282,  282,  282,  282,  282,  282,  141,  142,   69,   69,
      356,   65,   65,  220,  358,  220,   65,  210,   65,   65,
       65,   65,  284,  332,   69,   69,   69,   69,   65,   65,

       65,   65,   65,  233,   65,   65,   65,  313,   69,   65,
      285,   65,   65,  221,  304,  221,  303,   65,  293,  233,
       65,   65,  285,  268,  263,   65,  285,   69,   65,   69,
      254,  250,  242,   69,  286,  191,  189,  287,  288,  288,
      288,  288,   65,  185,  179,   65,  166,  165,  288,  288,
      288,  288,  288,  148,  147,   65,  132,   97,   66,   65,
       60,   59,  288,  288,  288,  288,  288,  288,  289,  289,
      289,  289,  360,  360,  360,  360,  360,  360,  289,  289,
      289,  289,  289,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  289,  289,  289,  289,  289,  289,  144,  144,

      144,  144,  360,  360,  360,  360,  360,  360,  144,  144,
      144,  144,  144,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  144,  144,  144,  144,  144,  144,  214,  214,
      214,  214,  360,  360,  360,  360,  360,  360,  214,  214,
      214,  214,  214,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  214,  214,  214,  214,  214,  214,  318,  318,
      318,  318,  360,  360,  360,  360,  360,  360,  318,  318,
      318,  318,  318,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  318,  318,  318,  318,  318,  318,  211,  211,
      211,  211,  360,  360,  360,  360,  360,   80,  211,  211,

      211,  211,  211,  360,  152,  360,  360,  360,  360,  153,
      360,  360,  211,  211,  211,  211,  211,  211,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  154,  360,  360,  360,  212,  322,  322,  322,  322,
      294,  360,  294,  360,  360,  294,  322,  322,  322,  322,
      322,  360,  294,  360,  360,  360,  294,  360,  360,  360,
      322,  322,  322,  322,  322,  322,  323,  323,  323,  323,
      360,  360,  360,  360,  360,  360,  323,  323,  323,  323,
      323,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      323,  323,  323,  323,  323,  323,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  324,  325,  325,  325,  325,
      360,  360,  360,  360,  360,  360,  325,  325,  325,  325,
      325,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      325,  325,  325,  325,  325,  325,  222,  222,  222,  222,
      360,  360,  360,  360,  360,  360,  222,  222,  222,  222,
      222,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      222,  222,  222,  222,  222,  222,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  223,  327,  327,  327,  327,  360,  360,

      360,  360,  360,  360,  327,  327,  327,  327,  327,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  327,  327,
      327,  327,  327,  327,  328,  328,  328,  328,  360,  360,
      360,  360,  360,  360,  328,  328,  328,  328,  328,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  328,  328,
      328,  328,  328,  328,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  329,  324,  324,  324,  324,  360,  360,
      360,  360,  360,  360,  324,  324,  324,  324,  324,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  324,  324,

      324,  324,  324,  324,  329,  329,  329,  329,  360,  360,
      360,  360,  360,  360,  329,  329,  329,  329,  329,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  329,  329,
      329,  329,  329,  329,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   61,  360,  360,   61,   61,   61,
       61,   61,   61,   61,   64,  360,   64,   64,   69,  360,
      360,   69,   69,   69,   69,   69,   69,   69,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  155,  360,
      360,  155,  155,  155,  360,  155,  164,  164,  199,  199,

      206,  360,  206,  206,  206,  206,  206,  206,  206,  206,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      215,  215,  217,  360,  217,  217,  217,  217,  217,  217,
      217,  217,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  232,  232,  232,  360,  232,  232,  232,  232,
      232,  232,  271,  271,  283,  283,  292,  292,  292,  360,
      292,  360,  292,  292,  360,  292,  319,  319,  326,  326,
      344,  344,  346,  346,    9,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360
    } ;

static const flex_int16_t yy_chk[1656] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       15,   18,   19,   22,   25,   23,   26,  359,   26,   26,
       26,   26,   32,   32,   25,   27,   22,   23,   18,  108,
       27,   29,   28,   29,   29,   29,   29,  108,   27,   33,

       33,   39,   19,   39,   15,   28,   46,   29,   28,   34,
       34,   28,   27,   28,   40,   41,   61,   40,   42,   28,
       46,   29,   28,   47,   48,   41,   48,   42,   41,   80,
       44,   28,   42,   41,   43,   55,   43,   47,   44,   28,
       45,   49,   43,   44,  356,   43,   45,   45,   44,   49,
       61,   80,   49,   45,   52,   52,   49,   50,   50,   50,
       50,   51,   53,   69,  317,   52,   81,   50,   50,   50,
       50,   50,   53,   81,   51,   83,   55,  317,   81,   51,
       84,   50,   50,   50,   50,   50,   50,   79,   79,   79,
       79,   86,   86,   69,   88,   88,   88,   83,   98,   50,

       81,   79,   84,  119,   50,   63,   63,  101,   85,   85,
       85,   85,   87,  119,   87,   79,   98,   87,   87,   87,
       87,   63,   85,  136,   90,  101,   90,   90,   90,   90,
       96,   96,   99,  100,  100,  100,   85,   63,  102,   63,
       90,  189,  110,  103,  102,  110,   99,  103,  105,  189,
      105,   63,  103,  109,   90,   63,   63,  136,   63,  109,
      103,  107,   63,   63,  107,  107,   63,   65,   65,   65,
       65,  113,  114,  125,  114,  113,  125,   65,   65,   65,
       65,   65,  115,  121,  115,  117,  117,  121,  355,  126,
      120,   65,   65,   65,   65,   65,   65,  120,  122,  126,

      120,  127,  122,  128,  128,  129,  133,  134,  133,  134,
      144,  127,  153,  172,   65,   71,   71,  135,  135,  129,
      135,  141,  142,  159,  159,  151,  351,  141,  142,  172,
      201,   71,  151,  135,  135,  135,  135,  151,  171,  150,
      144,  150,  133,  134,  150,  201,  169,   71,  153,   71,
      153,  150,  171,  153,  135,  150,  169,  141,  142,  151,
      153,   71,  152,  154,  153,   71,   71,  170,   71,  152,
      154,  350,   71,   71,  152,  154,   71,  123,  123,  123,
      123,  160,  160,  160,  160,  170,  177,  123,  123,  123,
      123,  123,  143,  143,  358,  156,  152,  154,  152,  143,

      177,  123,  123,  123,  123,  123,  123,  358,  143,  143,
      143,  143,  161,  161,  161,  161,  149,  156,  149,  123,
      137,  149,  149,  149,  149,  173,  156,  173,  156,  143,
      176,  156,  180,  137,  137,  137,  137,  180,  156,  163,
      163,  163,  156,  137,  137,  137,  137,  137,  176,  157,
      157,  157,  157,  178,  137,  187,  187,  137,  137,  137,
      137,  137,  137,  157,  158,  181,  158,  178,  349,  158,
      158,  158,  158,  162,  162,  162,  162,  157,  183,  181,
      137,  138,  138,  138,  138,  174,  174,  174,  182,  205,
      182,  138,  138,  138,  138,  138,  183,  185,  186,  194,

      191,  192,  192,  186,  194,  138,  138,  138,  138,  138,
      138,  197,  202,  185,  191,  193,  203,  193,  204,  269,
      202,  216,  217,  205,  269,  197,  204,  203,  138,  139,
      139,  139,  139,  206,  218,  220,  243,  243,  207,  139,
      139,  139,  139,  139,  225,  225,  225,  225,  247,  209,
      247,  216,  217,  139,  139,  139,  139,  139,  139,  145,
      226,  226,  226,  226,  218,  220,  246,  206,  145,  145,
      145,  145,  207,  227,  227,  227,  227,  246,  145,  145,
      145,  145,  145,  209,  248,  248,  228,  255,  228,  145,
      255,  228,  145,  145,  145,  145,  145,  145,  228,  229,

      231,  347,  228,  252,  252,  244,  229,  231,  230,  257,
      230,  229,  231,  230,  244,  145,  146,  146,  146,  146,
      230,  234,  249,  257,  230,  236,  146,  146,  146,  146,
      146,  258,  249,  229,  231,  237,  237,  237,  237,  258,
      146,  146,  146,  146,  146,  146,  273,  236,  238,  238,
      238,  238,  239,  239,  239,  239,  236,  234,  236,  234,
      273,  236,  234,  146,  198,  198,  198,  198,  236,  234,
      259,  259,  236,  234,  198,  198,  198,  198,  198,  240,
      240,  240,  240,  241,  241,  241,  241,  277,  198,  198,
      198,  198,  198,  198,  208,  208,  256,  208,  260,  265,

      261,  260,  256,  264,  275,  235,  264,  267,  285,  267,
      208,  345,  235,  305,  302,  265,  331,  235,  261,  275,
      302,  277,  290,  290,  290,  290,  208,  305,  208,  303,
      331,  208,  291,  291,  291,  291,  306,  306,  285,  235,
      208,  303,  311,  311,  208,  208,  307,  208,  235,  339,
      235,  208,  208,  235,  309,  208,  211,  211,  211,  211,
      235,  307,  309,  329,  235,  339,  211,  211,  211,  211,
      211,  295,  295,  295,  295,  296,  296,  296,  296,  315,
      211,  211,  211,  211,  211,  211,  212,  212,  212,  212,
      315,  310,  353,  329,  332,  332,  212,  212,  212,  212,

      212,  310,  312,  313,  324,  335,  353,  335,  312,  313,
      212,  212,  212,  212,  212,  212,  213,  213,  213,  213,
      348,  343,  342,  348,  318,  325,  213,  213,  213,  213,
      213,  318,  325,  336,  337,  341,  340,  336,  324,  337,
      213,  213,  213,  213,  213,  213,  214,  214,  214,  214,
      276,  276,  338,  276,  344,  346,  214,  214,  214,  214,
      214,  344,  346,  334,  333,  330,  276,  276,  276,  276,
      214,  214,  214,  214,  214,  214,  219,  219,  284,  284,
      352,  321,  320,  219,  357,  284,  352,  276,  316,  357,
      314,  308,  219,  304,  284,  284,  284,  284,  301,  300,

      299,  298,  297,  292,  274,  272,  266,  263,  219,  262,
      219,  254,  253,  219,  251,  284,  250,  245,  233,  232,
      200,  196,  219,  195,  190,  188,  219,  219,  184,  219,
      179,  175,  168,  219,  219,  118,  116,  219,  222,  222,
      222,  222,  112,  111,  106,  104,   93,   91,  222,  222,
      222,  222,  222,   78,   72,   64,   60,   38,   17,   16,
       14,   13,  222,  222,  222,  222,  222,  222,  223,  223,
      223,  223,    9,    0,    0,    0,    0,    0,  223,  223,
      223,  223,  223,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  223,  223,  223,  223,  223,  223,  224,  224,

      224,  224,    0,    0,    0,    0,    0,    0,  224,  224,
      224,  224,  224,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  224,  224,  224,  224,  224,  224,  268,  268,
      268,  268,    0,    0,    0,    0,    0,    0,  268,  268,
      268,  268,  268,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  268,  268,  268,  268,  268,  268,  270,  270,
      270,  270,    0,    0,    0,    0,    0,    0,  270,  270,
      270,  270,  270,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  270,  270,  270,  270,  270,  270,  278,  278,
      278,  278,    0,    0,    0,    0,    0,  294,  278,  278,

      278,  278,  278,    0,  294,    0,    0,    0,    0,  294,
        0,    0,  278,  278,  278,  278,  278,  278,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  294,    0,    0,    0,  278,  280,  280,  280,  280,
      294,    0,  294,    0,    0,  294,  280,  280,  280,  280,
      280,    0,  294,    0,    0,    0,  294,    0,    0,    0,
      280,  280,  280,  280,  280,  280,  281,  281,  281,  281,
        0,    0,    0,    0,    0,    0,  281,  281,  281,  281,
      281,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      281,  281,  281,  281,  281,  281,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  281,  282,  282,  282,  282,
        0,    0,    0,    0,    0,    0,  282,  282,  282,  282,
      282,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      282,  282,  282,  282,  282,  282,  286,  286,  286,  286,
        0,    0,    0,    0,    0,    0,  286,  286,  286,  286,
      286,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      286,  286,  286,  286,  286,  286,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  286,  288,  288,  288,  288,    0,    0,

        0,    0,    0,    0,  288,  288,  288,  288,  288,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  288,  288,
      288,  288,  288,  288,  289,  289,  289,  289,    0,    0,
        0,    0,    0,    0,  289,  289,  289,  289,  289,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  289,  289,
      289,  289,  289,  289,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  289,  322,  322,  322,  322,    0,    0,
        0,    0,    0,    0,  322,  322,  322,  322,  322,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  322,  322,

      322,  322,  322,  322,  327,  327,  327,  327,    0,    0,
        0,    0,    0,    0,  327,  327,  327,  327,  327,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  327,  327,
      327,  327,  327,  327,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  362,    0,    0,  362,  362,  362,
      362,  362,  362,  362,  363,    0,  363,  363,  364,    0,
        0,  364,  364,  364,  364,  364,  364,  364,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  367,    0,
        0,  367,  367,  367,    0,  367,  368,  368,  369,  369,

      370,    0,  370,  370,  370,  370,  370,  370,  370,  370,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      372,  372,  373,    0,  373,  373,  373,  373,  373,  373,
      373,  373,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  376,  376,  376,    0,  376,  376,  376,  376,
      376,  376,  377,  377,  378,  378,  379,  379,  379,    0,
      379,    0,  379,  379,    0,  379,  380,  380,  381,  381,
      382,  382,  383,  383,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
#include <parser.h>

int lines = 0;

using namespace std;
#line 1006 "lex.yy.c"
/* Numeric Literal Definitions*/
/* Comments Definitions */

#line 1010 "lex.yy.c"

#define INITIAL 0
#define template_head 1
#define template_start 2
#define template_component 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 67 "scanner.l"



#line 1234 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 361 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1585 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 70 "scanner.l"
{  return COMMENT;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 72 "scanner.l"
{	// Regex Literal
											return REGEX_LITERAL;
										}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 76 "scanner.l"
{ return NULL_L; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 78 "scanner.l"
{
								return STRING_L;
							}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 81 "scanner.l"
{
								return STRING_L;
							}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 85 "scanner.l"
{
								yylval.decimal = atof(yytext);
								return DECIMAL_L;
							}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 90 "scanner.l"
{
								return BINARY_L;
							}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "scanner.l"
{
								return OCTAL_L;
							}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "scanner.l"
{
								return HEX_L;
							}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 102 "scanner.l"
{
							return BooleanLiteral;
						}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "scanner.l"
{ return BREAK; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "scanner.l"
{ return DO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "scanner.l"
{ return IN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "scanner.l"
{ return TYPEOF; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "scanner.l"
{ return CASE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "scanner.l"
{ return ELSE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "scanner.l"
{ return INSTANCEOF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "scanner.l"
{ return VAR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "scanner.l"
{ return CATCH; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "scanner.l"
{ return EXPORT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "scanner.l"
{ return NEW; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "scanner.l"
{ return VOID; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 118 "scanner.l"
{ return CLASS; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "scanner.l"
{ return EXTENDS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "scanner.l"
{ return RETURN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 121 "scanner.l"
{ return WHILE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "scanner.l"
{ return CONST; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "scanner.l"
{ return FINALLY; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "scanner.l"
{ return SUPER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "scanner.l"
{ return WITH; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "scanner.l"
{ return CONTINUE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 127 "scanner.l"
{ return FOR; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "scanner.l"
{ return SWITCH; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "scanner.l"
{ return YIELD; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "scanner.l"
{ return DEBUGGER; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "scanner.l"
{ return FUNCTION; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 132 "scanner.l"
{ return THIS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 133 "scanner.l"
{ return DEFAULT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "scanner.l"
{ return IF; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 135 "scanner.l"
{ return THROW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 136 "scanner.l"
{ return DELETE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "scanner.l"
{ return IMPORT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "scanner.l"
{ return TRY; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "scanner.l"
{ return AWAIT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 140 "scanner.l"
{ return ENUM; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 141 "scanner.l"
{ return '{'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 142 "scanner.l"
{ return '}'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 143 "scanner.l"
{ return '('; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 144 "scanner.l"
{ return ')'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "scanner.l"
{ return '['; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 146 "scanner.l"
{ return ']'; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 147 "scanner.l"
{ return '.'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 148 "scanner.l"
{ return TDOT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 149 "scanner.l"
{ return ';'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 150 "scanner.l"
{ return ','; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 151 "scanner.l"
{ return '<'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 152 "scanner.l"
{ return '>'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 153 "scanner.l"
{ return LE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 154 "scanner.l"
{ return GE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 155 "scanner.l"
{ return EQ; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 156 "scanner.l"
{ return DIFF; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 157 "scanner.l"
{ return EQTYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 158 "scanner.l"
{ return DFTYPE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 159 "scanner.l"
{ return '+'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 160 "scanner.l"
{ return '-'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 161 "scanner.l"
{ return '*'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 162 "scanner.l"
{ return '%'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 163 "scanner.l"
{ return INCREASE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 164 "scanner.l"
{ return DECREASE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 165 "scanner.l"
{ return LSHIFT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 166 "scanner.l"
{ return RSHIFT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 167 "scanner.l"
{ return URSHIFT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 168 "scanner.l"
{ return '&'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 169 "scanner.l"
{ return '|'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 170 "scanner.l"
{ return '^'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 171 "scanner.l"
{ return '!'; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 172 "scanner.l"
{ return '~'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 173 "scanner.l"
{ return LOGAND; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 174 "scanner.l"
{ return LOOR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 175 "scanner.l"
{ return '?'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 176 "scanner.l"
{ return ':'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 177 "scanner.l"
{ return '='; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 178 "scanner.l"
{ return ADDASS; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 179 "scanner.l"
{ return SUBASS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 180 "scanner.l"
{ return MULASS; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 181 "scanner.l"
{ return REMASS; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 182 "scanner.l"
{ return LSHIFTASS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 183 "scanner.l"
{ return RSHIFTASS; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 184 "scanner.l"
{ return URSHIFTASS; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 185 "scanner.l"
{ return BWANDASS; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 186 "scanner.l"
{ return BWORASS; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 187 "scanner.l"
{ return BWXORASS; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 188 "scanner.l"
{ return ARROWF; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 189 "scanner.l"
{ return EXP; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 190 "scanner.l"
{ return EXPASS; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 191 "scanner.l"
{ return '/'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 192 "scanner.l"
{ return DIVASS; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 194 "scanner.l"
{ yylval.ident = _strdup(yytext); return IDENT; }
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 196 "scanner.l"
{ return LINE_TERM; }
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 198 "scanner.l"
/* skip whitespace */
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 200 "scanner.l"
{
                                fprintf(stderr, "invalid character '%c'\n", *yytext);
                            }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 203 "scanner.l"
ECHO;
	YY_BREAK
#line 1826 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(template_head):
case YY_STATE_EOF(template_start):
case YY_STATE_EOF(template_component):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 361 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 361 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 360);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 203 "scanner.l"



int yywrap() {
	return 1;
}

void yyerror(char* message) {
	fprintf(stderr, "Error: line %d, %s\n", lines, message);
}

